vuln-0013: run `cargo minimize` until crash
Build cargo-minimize from forked version to insert `panic!("CARGO_MINIMIZE_PANIC_FAIL") instead of
`loop {}`

RUST_BACKTRACE=1 cargo minimize --script-path ./run_test.sh --skip-privating --ignore-file src/slice/api.rs --ignore-file src/slice/iter.rs --ignore-file src/vec.rs

 cargo_minimize::processor::Starting round of pass{name="delete-unused-functions"}

thread 'main' panicked at src/processor/reaper.rs:208:17:
assertion `left == right` failed: encountered multiline span in dead_code
  left: 55
 right: 58